//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""Bar"",
            ""id"": ""a2d2f10f-912a-4e80-b535-523a35260080"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""55ed5faa-db3d-4390-b53e-c1c79ffd73d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""016e5e4e-6d91-411e-a3b6-2b583c4bbb79"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Bar
        m_Bar = asset.FindActionMap("Bar", throwIfNotFound: true);
        m_Bar_Click = m_Bar.FindAction("Click", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Bar
    private readonly InputActionMap m_Bar;
    private List<IBarActions> m_BarActionsCallbackInterfaces = new List<IBarActions>();
    private readonly InputAction m_Bar_Click;
    public struct BarActions
    {
        private @InputControls m_Wrapper;
        public BarActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_Bar_Click;
        public InputActionMap Get() { return m_Wrapper.m_Bar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BarActions set) { return set.Get(); }
        public void AddCallbacks(IBarActions instance)
        {
            if (instance == null || m_Wrapper.m_BarActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BarActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
        }

        private void UnregisterCallbacks(IBarActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
        }

        public void RemoveCallbacks(IBarActions instance)
        {
            if (m_Wrapper.m_BarActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBarActions instance)
        {
            foreach (var item in m_Wrapper.m_BarActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BarActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BarActions @Bar => new BarActions(this);
    public interface IBarActions
    {
        void OnClick(InputAction.CallbackContext context);
    }
}
